"""Tool to assist `metricflow` / `dbt-metricflow` PyPi releases. These are heavily generated by AI."""
from __future__ import annotations

from metricflow_semantics.toolkit.directory_anchor import DirectoryAnchor

RELEASE_TOOL_DIRECTORY_ANCHOR = DirectoryAnchor()
