from __future__ import annotations

import itertools
import logging
from abc import ABC, abstractmethod
from collections.abc import Mapping, Sequence

from metricflow_semantics.specs.instance_spec import InstanceSpec
from metricflow_semantics.specs.query_spec import InputSpecOrder
from metricflow_semantics.specs.spec_set import (
    InstanceSpecSet,
    InstanceSpecSetTransform,
)
from metricflow_semantics.toolkit.mf_logging.lazy_formattable import LazyFormat
from typing_extensions import override

from metricflow.sql.sql_plan import SqlSelectColumn

logger = logging.getLogger(__name__)


class OutputColumnOrderer(ABC):
    """Defines how output columns should be ordered in a rendered `SELECT` statement."""

    @abstractmethod
    def order_columns(
        self, spec_to_columns_mapping: Mapping[InstanceSpec, Sequence[SqlSelectColumn]]
    ) -> Sequence[SqlSelectColumn]:
        """Return select columns in output order for the given spec-to-columns mapping."""
        pass


class LegacyTypeGroupedOrderer(OutputColumnOrderer):
    """Group columns by spec type while preserving the arbitrary order generated by the engine."""

    @override
    def order_columns(
        self, spec_to_columns_mapping: Mapping[InstanceSpec, Sequence[SqlSelectColumn]]
    ) -> Sequence[SqlSelectColumn]:
        spec_set = InstanceSpecSet.create_from_specs(spec_to_columns_mapping)
        specs_in_order = tuple(
            itertools.chain(
                spec_set.time_dimension_specs,
                spec_set.entity_specs,
                spec_set.dimension_specs,
                spec_set.group_by_metric_specs,
                spec_set.metric_specs,
                spec_set.simple_metric_input_specs,
                spec_set.metadata_specs,
            )
        )
        select_columns: list[SqlSelectColumn] = []
        for spec in specs_in_order:
            select_columns.extend(spec_to_columns_mapping[spec])

        return select_columns


class TypeGroupedOrderer(OutputColumnOrderer):
    """Group columns by spec type while preserving the relative order from the query input within each group."""

    def __init__(self, input_spec_order: InputSpecOrder) -> None:  # noqa: D107
        self._input_spec_order = input_spec_order

    @override
    def order_columns(
        self, spec_to_columns_mapping: Mapping[InstanceSpec, Sequence[SqlSelectColumn]]
    ) -> Sequence[SqlSelectColumn]:
        try:
            specs_in_order = TypeGroupedOrderer._OrderByTypeTransform(self._input_spec_order).transform(
                InstanceSpecSet.create_from_specs(spec_to_columns_mapping)
            )
            select_columns: list[SqlSelectColumn] = []
            for spec in specs_in_order:
                select_columns.extend(spec_to_columns_mapping[spec])

            return select_columns
        except Exception:
            logger.exception("Error resolving output column order falling back to legacy order")
            return LegacyTypeGroupedOrderer().order_columns(spec_to_columns_mapping)

    class _OrderByTypeTransform(InstanceSpecSetTransform):
        def __init__(self, input_spec_order: InputSpecOrder) -> None:  # noqa: D107
            self._input_spec_order = input_spec_order
            self._spec_to_input_order_key: dict[InstanceSpec, int] = {}

            for i, instance_spec in enumerate(
                itertools.chain(input_spec_order.group_by_item_specs, input_spec_order.metric_specs)
            ):
                self._spec_to_input_order_key[instance_spec] = i

        def transform(self, spec_set: InstanceSpecSet) -> Sequence[InstanceSpec]:
            def _key(spec: InstanceSpec) -> int:
                input_order_key = self._spec_to_input_order_key.get(spec)
                if input_order_key is None:
                    raise RuntimeError(
                        LazyFormat(
                            "Spec missing from the input order. Check that the input spec order and the output spec generation.",
                            missing_spec=spec,
                            input_spec_order=self._spec_to_input_order_key,
                        )
                    )
                return input_order_key

            result = tuple(
                itertools.chain(
                    sorted(spec_set.time_dimension_specs, key=_key),
                    sorted(spec_set.entity_specs, key=_key),
                    sorted(spec_set.dimension_specs, key=_key),
                    sorted(spec_set.group_by_metric_specs, key=_key),
                    sorted(spec_set.metric_specs, key=_key),
                    sorted(spec_set.simple_metric_input_specs, key=_key),
                    sorted(spec_set.metadata_specs, key=_key),
                )
            )

            return result


class InputOrderPreservingOrderer(OutputColumnOrderer):
    """Return columns in the order that specs were provided in the query input."""

    def __init__(self, input_spec_order: InputSpecOrder) -> None:  # noqa: D107
        self._input_spec_order = input_spec_order

    @override
    def order_columns(
        self, spec_to_columns_mapping: Mapping[InstanceSpec, Sequence[SqlSelectColumn]]
    ) -> Sequence[SqlSelectColumn]:
        results: list[SqlSelectColumn] = []

        for spec in self._input_spec_order.group_by_item_specs + self._input_spec_order.metric_specs:
            select_columns = spec_to_columns_mapping.get(spec)
            if select_columns is None:
                logger.error(
                    LazyFormat(
                        "Spec missing from select column mapping. Check generation of `input_spec_order`"
                        " and `spec_to_columns_mapping`. Falling back to legacy column order.",
                        missing_spec=spec,
                        input_spec_order=self._input_spec_order,
                    )
                )
                return LegacyTypeGroupedOrderer().order_columns(spec_to_columns_mapping)
            results.extend(select_columns)

        return results
