changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
versionHeaderPath: ""
changelogPath: CHANGELOG.md
versionExt: md
envPrefix: "CHANGIE_"
versionFormat: '## MetricFlow {{.Version}} - {{.Time.Format "January 02, 2006"}}'
kindFormat: '### {{.Kind}}'
changeFormat: |-
  {{- $IssueList := list }}
  {{- $changes := splitList " " $.Custom.Issue }}
  {{- range $issueNbr := $changes }}
    {{- if atoi $issueNbr }}
      {{- $changeLink := "[#nbr](https://github.com/dbt-labs/metricflow/issues/nbr)" | replace "nbr" $issueNbr }}
      {{- $IssueList = append $IssueList $changeLink  }}
    {{- end -}}
  {{- end -}}
  - {{.Body}}{{if $IssueList}} ({{ join ", " $IssueList }}){{end}}

kinds:
  - label: Breaking Changes
  - label: Features
  - label: Fixes
  - label: Docs
  - label: Under the Hood
  - label: Dependencies
  - label: Security

newlines:
  afterChangelogHeader: 1
  afterKind: 1
  afterChangelogVersion: 1
  beforeKind: 1
  endOfVersion: 1

custom:
- key: Author
  label: GitHub Username(s) (separated by a single space if multiple)
  type: string
  minLength: 3
- key: Issue
  label: "GitHub Issue (or PR) Number(s) (separated by a single space if multiple)"
  type: string
  minLength: 1

footerFormat: |
  {{- $contributorDict := dict }}
  {{- /* ensure we always skip snyk and dependabot in addition to the core team */}}
  {{- $maintainers := list "dependabot[bot]" "snyk-bot"}}
  {{- range $change := .Changes }}
    {{- $authorList := splitList " " $change.Custom.Author }}
    {{- /* loop through all authors for a single changelog */}}
    {{- range $author := $authorList }}
      {{- $authorLower := lower $author }}
      {{- /* we only want to include non-core team contributors */}}
      {{- if not (has $authorLower $maintainers)}}
        {{- $IssueList := list }}
        {{- $changeLink := $change.Kind }}
        {{- $changes := splitList " " $change.Custom.Issue }}
        {{- range $issueNbr := $changes }}
          {{- if atoi $issueNbr }}
            {{- $changeLink := "[#nbr](https://github.com/dbt-labs/metricflow/issues/nbr)" | replace "nbr" $issueNbr }}
            {{- $IssueList = append $IssueList $changeLink  }}
          {{- end -}}
        {{- end -}}
        {{- /* check if this contributor has other changes associated with them already */}}
        {{- if hasKey $contributorDict $author }}
          {{- $contributionList := get $contributorDict $author }}
          {{- $contributionList = concat $contributionList $IssueList  }}
          {{- $contributorDict := set $contributorDict $author $contributionList }}
        {{- else }}
          {{- $contributionList := $IssueList }}
          {{- $contributorDict := set $contributorDict $author $contributionList }}
        {{- end }}
      {{- end}}
    {{- end}}
  {{- end }}
  {{- /* no indentation here for formatting so the final markdown doesn't have unneeded indentations */}}
  {{- if $contributorDict}}
  ### Contributors
  {{- range $k,$v := $contributorDict }}
  - [@{{$k}}](https://github.com/{{$k}}){{if $v}} ({{ join ", " $v }}){{end}}
  {{- end }}
  {{- end }}