version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "metricflow"
      POSTGRES_PASSWORD: "metricflowing"
      POSTGRES_DB: "metricflow"
