from __future__ import annotations

import logging
from typing import List

import jinja2
from dbt_semantic_interfaces.protocols.where_filter import WhereFilter

from metricflow.specs.column_assoc import ColumnAssociationResolver
from metricflow.specs.specs import DimensionSpec, EntitySpec, LinkableSpecSet, TimeDimensionSpec, WhereFilterSpec
from metricflow.specs.where_filter_dimension import WhereFilterDimensionFactory
from metricflow.specs.where_filter_entity import WhereFilterEntityFactory
from metricflow.specs.where_filter_time_dimension import WhereFilterTimeDimensionFactory
from metricflow.sql.sql_bind_parameters import SqlBindParameters

logger = logging.getLogger(__name__)


class RenderSqlTemplateException(Exception):  # noqa: D
    pass


class WhereSpecFactory:
    """Renders the SQL template in the WhereFilter and converts it to a WhereFilterSpec."""

    def __init__(  # noqa: D
        self,
        column_association_resolver: ColumnAssociationResolver,
        bind_parameters: SqlBindParameters = SqlBindParameters(),
    ) -> None:
        self._column_association_resolver = column_association_resolver
        self._bind_parameters = bind_parameters

    def create_from_where_filter(self, where_filter: WhereFilter) -> WhereFilterSpec:  # noqa: D
        dimension_specs: List[DimensionSpec] = []
        time_dimension_specs: List[TimeDimensionSpec] = []
        entity_specs: List[EntitySpec] = []

        # Used to check that call parameter sets generated by DSI match those generated below.
        call_parameter_sets = where_filter.call_parameter_sets

        try:
            rendered_sql_template = jinja2.Template(
                where_filter.where_sql_template, undefined=jinja2.StrictUndefined
            ).render(
                {
                    "Dimension": WhereFilterDimensionFactory(
                        call_parameter_sets, dimension_specs, self._column_association_resolver
                    ).create,
                    "TimeDimension": WhereFilterTimeDimensionFactory(
                        call_parameter_sets, time_dimension_specs, self._column_association_resolver
                    ).create,
                    "Entity": WhereFilterEntityFactory(
                        call_parameter_sets, entity_specs, self._column_association_resolver
                    ).create,
                }
            )
        except (jinja2.exceptions.UndefinedError, jinja2.exceptions.TemplateSyntaxError) as e:
            raise RenderSqlTemplateException(
                f"Error while rendering Jinja template:\n{where_filter.where_sql_template}"
            ) from e

        return WhereFilterSpec(
            where_sql=rendered_sql_template,
            bind_parameters=self._bind_parameters,
            linkable_spec_set=LinkableSpecSet(
                dimension_specs=tuple(dimension_specs),
                time_dimension_specs=tuple(time_dimension_specs),
                entity_specs=tuple(entity_specs),
            ),
        )
