from __future__ import annotations

import logging
from abc import ABC, abstractmethod

from metricflow_semantics.experimental.dataclass_helpers import fast_frozen_dataclass
from metricflow_semantics.experimental.dsi.manifest_object_lookup import ManifestObjectLookup
from metricflow_semantics.experimental.mf_graph.path_finding.path_finder import MetricflowGraphPathFinder
from metricflow_semantics.experimental.semantic_graph.attribute_resolution.attribute_computation_path import (
    AttributeRecipeWriterPath,
)
from metricflow_semantics.experimental.semantic_graph.sg_interfaces import (
    MutableSemanticGraph,
    SemanticGraph,
    SemanticGraphEdge,
    SemanticGraphNode,
)

logger = logging.getLogger(__name__)


@fast_frozen_dataclass()
class SubgraphGeneratorArgumentSet:
    """Groups arguments for the subgraph generator to facilitate updates."""

    manifest_object_lookup: ManifestObjectLookup
    path_finder: MetricflowGraphPathFinder[SemanticGraphNode, SemanticGraphEdge, AttributeRecipeWriterPath]


class SemanticSubgraphGenerator(ABC):
    """Generates a specific portion of the semantic graph.

    As the semantic graph has many elements, it's helpful to break down the generation of the graph into logical pieces.
    For example, the `TimeEntitySubgraphGenerator` creates a subgraph only containing the nodes and edges related to the
    time entities.

    To create the complete semantic graph, the output of each generator is combined into a single graph.
    """

    def __init__(self, argument_set: SubgraphGeneratorArgumentSet) -> None:  # noqa: D107
        self._manifest_object_lookup = argument_set.manifest_object_lookup
        self._path_finder = argument_set.path_finder

    @abstractmethod
    def generate_subgraph(self, predecessor_graph: SemanticGraph) -> MutableSemanticGraph:
        """Generate the subgraph that corresponds to this generator.

        Args:
            predecessor_graph: The semantic graph as generated by previously run subgraph generators. Some subgraph
            generators rely on semantic context added by other subgraph generators. e.g. the group-by metric
            subgraph generator relies on join relationships added by the `EntityJoinSubgraphGenerator`.

        Returns: A subgraph containing the nodes and edges that should be added to `current_graph`.

        """
        raise NotImplementedError
