name: ☣️ Regression
description: Report a regression you've observed in a newer version of metricflow
title: "[Regression] <title>"
labels: ["bug", "regression", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this regression report!
  - type: checkboxes
    attributes:
      label: Is this a regression in a recent version of metricflow?
      description: >
        A regression is when documented functionality works as expected in an older version of metricflow,
        and no longer works after upgrading to a newer version of metricflow
      options:
        - label: I believe this is a regression in metricflow functionality
          required: true
        - label: I have searched the existing issues, and I could not find an existing issue for this regression
          required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected/Previous Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        If applicable, log output to help explain your problem.
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Python**: 3.9.12 (`python3 --version`)
          - **metricflow (working version)**: 0.14.0
          - **metricflow (regression version)**: 0.15.0
      value: |
        - OS:
        - Python:
        - metricflow (working version):
        - metricflow (regression version):
      render: markdown
    validations:
      required: true
  - type: dropdown
    id: database
    attributes:
      label: Which database adapter are you using with metricflow?
      description: If the regression is specific to the database or adapter, please open the issue in that adapter's repository instead
      multiple: true
      options:
        - postgres
        - redshift
        - snowflake
        - bigquery
        - spark
        - other (mention it in "Additional Context")
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
