name: Run MetricFlow Tests
description: Runs MetricFlow using the specified Python version and engine settings.

inputs:
  python-version:
    description: "Version of Python to use for testing."
    required: true
  mf_sql_engine_url:
    description: "URL for configuring SQL engine connection."
    required: false
    default: "duckdb://"
  mf_sql_engine_password:
    description: "Password for configuring the SQL engine connection."
    required: false
    default: ""
  parallelism:
    description: "How many tests to run in parallel. auto = # of cores."
    required: false
    default: "auto"
  make-target:
    description: "The target to use for the make command."
    required: false
    default: "test"
runs:
  using: "composite"
  steps:
  - name: Setup Python ${{ inputs.python-version }} Environment
    uses: ./.github/actions/setup-python-env
    with:
      python-version: "${{ inputs.python-version }}"
  - name: Run Tests
    shell: bash
    run: make -e PARALLELISM=${{ inputs.parallelism }} ${{ inputs.make-target }}
    env:
      MF_SQL_ENGINE_URL: ${{ inputs.mf_sql_engine_url }}
      MF_SQL_ENGINE_PASSWORD: ${{ inputs.mf_sql_engine_password }}
      METRICFLOW_CLIENT_EMAIL: ci-tester@gmail.com