name: Publish Metricflow Release
on:
  workflow_dispatch:
  push:
    # MetricFlow historically tagged releases with v<pep440_semantic_version>
    # We restrict to this for now and assume any tag without a package identifier is MetricFlow itself
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: Pypi Publish
      url: https://pypi.org/p/metricflow
    permissions:
      id-token: write
    steps:
      - name: Check-out the repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # actions/checkout@v4

      - uses: ./.github/actions/setup-python-env

      - name: Build `metricflow` package
        run: hatch build

      - name: Publish `metricflow` package to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # pypa/gh-action-pypi-publish@release/v1
