name: Publish dbt-metricflow Release
on:
  workflow_dispatch:
  push:
    # Tag format is <package>/v<pep440_semantic_version>
    tags:
      - "dbt-metricflow/v[0-9]+.[0-9]+.[0-9]+*"

env:
  PYTHON_VERSION: "3.8"

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment: Pypi Publish
    steps:
      - name: Check-out the repo
        uses: actions/checkout@v3

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Hatch Publish `dbt-metricflow`
        working-directory: ./dbt-metricflow
        run: hatch build && hatch publish
