name: Publish dbt-metricflow Release
on:
  workflow_dispatch:
  push:
    # Tag format is <package>/v<pep440_semantic_version>
    tags:
      - "dbt-metricflow/v[0-9]+.[0-9]+.[0-9]+*"
jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: Pypi Publish
      url: https://pypi.org/p/dbt-metricflow
    permissions:
      id-token: write
    steps:
      - name: Check-out the repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-env
      - name: Build `dbt-metricflow` package
        working-directory: ./dbt-metricflow
        run: hatch build
      - name: Publish `dbt-metricflow` package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./dbt-metricflow/dist/
