name: Check `pip install dbt-metricflow`
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:

  metricflow-pip-install-tests:
    name: MetricFlow `pip` Install Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12" ]
    steps:

      - name: Check-out the repo
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }} Environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Run `pip install dbt-metricflow`
        run: "pip install dbt-metricflow"
